name: "Download File"
description: "Download a file from a given URL"
inputs:
  github-repo:
    description: "The GitHub repository to download the file from"
    required: true
  osArch:
    description: "The OS architecture to download the file for"
    required: true
  output-file-path:
    description: "The local file path to save the downloaded file"
    required: true
  auth-token:
    description: "The GitHub auth token to use for downloading the file"
    required: true
  outputDir:
    description: "The local directory path to save the downloaded file"
    required: true
outputs:
  downloaded-file-path:
    description: "The local file path of the downloaded file"
runs:
  using: 'node12'
  main: 'dist/index.js'
